Update dependencies and fix compiler errors with recent DMD (v2.109.9)
aminya/d-tree-sitter pull request #11
Opened 2024-07-02 08:53 UTC by stonemaster

2024-07-02 09:36 UTC, aminya approved these changes

2024-07-02 09:36 UTC, aminya requested changes
Could you update the CI as well?

2024-07-02 09:45 UTC, stonemaster commented
Sure, I am happy to check what's going on with the CI!

What is your opinion on the compiler versions used: should the old versions be replaced by recent LDC/DMD versions? At a first glance there are some random looking build errors but I don't know whether they are related to old compiler versions ..

2024-07-02 16:23 UTC, aminya commented
Yes, I am fine dropping support for old compilers as long as we bump the major version

2024-07-03 21:31 UTC, aminya commented
Sub flags are deprecated for dmd, they should be removed from the dub file

2024-07-03 22:25 UTC, aminya commented on .github/workflows/CI.yml
> +          - 18.0.0
```suggestion
           # default setup-cpp version 
          - true
```

2024-07-04 20:17 UTC, aminya commented on .github/workflows/CI.yml
> +          - ubuntu-24.04
```suggestion
          - ubuntu-22.04
```

2024-07-10 07:05 UTC, stonemaster commented
Thanks for the last commits. It seems that two build configurations failed because of "out of memory" :-| 

Locally the `lint` command runs fine for me but outputs the following strange error:
```
...d-tree-sitter/script/lib/meson.d(0:0)[warn]: Variable  is never modified and could have been declared const or immutable.
```

2024-07-11 05:00 UTC, aminya commented on .github/workflows/CI.yml
> +          - macos-13.0
```suggestion
          - macos-13
```

2024-07-12 07:19 UTC, aminya approved these changes

2024-07-12 07:19 UTC, merged